# Goal: I have to lint, build, test the code for frontend and backend, and then push the images to Dockerhub. 

name: CI

on:
  push:
    branches: [master]

jobs: 
    frontend: 
        # GitHub Runner available on Ubuntu, Windows, and macOS. Here we are using Ubuntu.
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v7
            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '20'
                cache: 'npm'
                cache-dependency-path: frontend/package-lock.json
            - name: Install packages
              run: npm install
              working-directory: frontend
            - name: Lint code
              run: npm run lint
              working-directory: frontend
            - name: Run tests
              run: npm test
              working-directory: frontend
            - name: Docker login 
              uses: docker/login-action@v2
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Docker build and push
              uses: docker/build-push-action@v7
              with:
                context: ./frontend
                push: true
                tags: ${{ vars.DOCKER_USERNAME }}/devboard-frontend:latest
    backend: 
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v7
            - name: Setup Node.js
              uses: actions/setup-go@v6
              with:
                go-version: '1.23'
                go-version-file: backend/go.mod
                cache-dependency-path: backend/go.sum
            - name: Run go formatter
              run: go fmt
              working-directory: backend
            - name: Run go vet
              run: go vet
              working-directory: backend
            - name: Run tests
              run: go test
              working-directory: backend
            - name: Docker login 
              uses: docker/login-action@v2
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Docker build and push
              uses: docker/build-push-action@v7
              with:
                context: ./backend
                push: true
                tags: ${{ vars.DOCKER_USERNAME }}/devboard-backend:latest